### ISSUE TITLE
Running Dockerized?

### ISSUE THREAD

**Issue by prologic** [damicon/zfswatcher#9]
Just wondering whether you've tried to run this Dockerized at all and if that worked? I imagine you'd have to run it as a "privileged" container with ``ledctl`` and ``zfs`` installed in the container's image?

**Comment by falconn19** [comment]
No I have not tried to run it in a vm or a container, but I think it would still give me the same results.  I would still have to complie zfs-fuse-arm for the container, and I think it would still be missing the status line in the "zpool status" command.

**Comment by prologic** [comment]
Hmm you could be right :)

**Comment by snabb** [comment]
Zfswatcher does not need any special access privileges to the system. It just needs output from some ZFS commands as input. You can run it in any container you wish. Just change zfswatcher.conf settings `zpoolstatuscmd`, `zfslistcmd`, `zfslistusagecmd`, `zpooliostatcmd` and `ledctlcmd`to some other command which pulls the desired input from the ZFS system. It does not use any other interface to the ZFS component than these configurable commands. While developing and testing Zfswatcher I have defined these commands just as `cat /tmp/zpoolstatus.txt` etc. and edited the text file to simulate various different potential error scenarios. Other times I have defined these commands to be executed over ssh connection using public key authentication. Feel free to customize.

**Comment by prologic** [comment]
So what you're saying is "something" needs to spit out ``zpool status`` to a file somewhere on the host and a Dockerized container of ``zfswatcher`` can monitor this file, parser it and run independently? Obviously you won't get any of the led control though I assume.

**Comment by snabb** [comment]
There many alternative ways to implement this. Passing the command output through a file is one possibility. Another approach would be to use `xinetd` or similar to set up TCP ports on the ZFS host to listen to incoming connections and execute the required ZFS commands with the output directed to the socket. In the Zfswatcher side you would use `nc` or similar command to connect to those TCP ports to fetch the command output.

As you said none of these options really work with `ledctl` because Zfswatcher needs to supply a varying command line to that command. Running the `ledctl` command over `ssh` (or `rsh` if anyone still uses that) would work though but that might be a security issue (if improving security is the goal in containerizing Zfswatcher). You might be able to utilize `ssh` with a dedicated `ledctl` user account with a `ForceCommand` in `sshd_config` or `command=` in `authorized_keys` with a script which takes the command line from `SSH_ORIGINAL_COMMAND` environment variable and feeds it to `ledctl` on the ZFS host.

**Comment by prologic** [comment]
Thanks I'll try a few things and see how it works out :)
